version: "3.7"

volumes:
  chain_config:

services:
  build-provider-image:
    build:
      context: chain/images/provider-vm
    image: band-provider:latest

  single-validator:
    build:
      context: chain
      dockerfile: Dockerfile
    image: band-validator:latest
    environment:
      - PRIVATE_KEY=06be35b56b048c5a6810a47e2ef612eaed735ccb0d7ea4fc409f23f1d1a16e0b
      - NODE_URI=tcp://localhost:26657
    volumes:
      - chain_config:/root/.bandd/config/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      bandchain:
        ipv4_address: 172.18.0.11
    depends_on:
      - build-provider-image
      - code-server
      - proxy-server
    ports:
      - 26657:26657
    command: sh -c "chmod +x ./docker-config/single-validator/run.sh && ./docker-config/single-validator/run.sh"

  multi-validator:
    image: tianon/true
    restart: "no"
    networks:
      bandchain:
    depends_on:
      - multi-validator1-node
      - multi-validator2-node
      - multi-validator3-node
      - multi-validator4-node
      - build-provider-image
      - code-server
      - proxy-server

  multi-validator1-node:
    build:
      context: chain
      dockerfile: Dockerfile
    image: band-validator:latest
    environment:
      - PRIVATE_KEY=06be35b56b048c5a6810a47e2ef612eaed735ccb0d7ea4fc409f23f1d1a16e0b
      - NODE_URI=tcp://localhost:26657
    ports:
      - 26657:26657
    volumes:
      - chain_config:/root/.bandd/config/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      bandchain:
        ipv4_address: 172.18.0.11
    command: sh -c "chmod +x ./docker-config/run.sh && ./docker-config/run.sh validator1"

  multi-validator2-node:
    image: band-validator:latest
    environment:
      - PRIVATE_KEY=6abc8ab25298fb4af6adcb9d5831db0ad7c959388f0d947abd2b4c4457ef52ec
      - NODE_URI=tcp://localhost:26657
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      bandchain:
        ipv4_address: 172.18.0.12
    command: sh -c "chmod +x ./docker-config/run.sh && ./docker-config/run.sh validator2"

  multi-validator3-node:
    image: band-validator:latest
    environment:
      - PRIVATE_KEY=894fc1c7e7666c722ae5f30ba4cb18c546e08f0b2634718c27b80b9d39416dbe
      - NODE_URI=tcp://localhost:26657
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      bandchain:
        ipv4_address: 172.18.0.13
    command: sh -c "chmod +x ./docker-config/run.sh && ./docker-config/run.sh validator3"

  multi-validator4-node:
    image: band-validator:latest
    environment:
      - PRIVATE_KEY=947f1715251d43de45232fc072e3ca4d823e876cf9f4ef74ad9a5f4ef440937e
      - NODE_URI=tcp://localhost:26657
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      bandchain:
        ipv4_address: 172.18.0.14
    command: sh -c "chmod +x ./docker-config/run.sh && ./docker-config/run.sh validator4"

  rest-server:
    image: band-validator:latest
    networks:
      bandchain:
        ipv4_address: 172.18.0.15
    restart: always
    ports:
      - 1317:1317
    command: bandcli rest-server --laddr tcp://0.0.0.0:1317 --node tcp://172.18.0.11:26657 --chain-id bandchain

  proxy-server:
    build:
      context: scan/proxy
    image: proxy-server:latest
    networks:
      bandchain:
        ipv4_address: 172.18.0.99
    depends_on:
      - rest-server
    ports:
      - 80:80

  code-server:
    image: band-validator:latest
    environment:
      - PORT=5000
      - NODE_URI=tcp://172.18.0.11:26657
      - QUERY_URI=http://172.18.0.15:1317
      - PRIVATE_KEY=eedda7a96ad35758f2ffc404d6ccd7be913f149a530c70e95e2e3ee7a952a877
    networks:
      bandchain:
        ipv4_address: 172.18.0.16
    ports:
      - 5000:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    depends_on:
      - build-provider-image
    command: sh -c "cd ./cmd/bandsv && go run *"

  owasm-server:
    build: ./studio/server
    image: owasm-server:latest
    ports:
      - 8082:8082

  owasm-studio:
    build: ./studio/ui
    image: owasm-studio:latest
    depends_on:
      - owasm-server
    ports:
      - 28443:28443

networks:
  bandchain:
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"
