[package]
name = "owasm"
version = "0.1.7"
authors = ["Band Protocol <connect@bandprotocol.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/bandprotocol/bandchain/tree/master/owasm"
description = """
TODO
"""

[dependencies]
json = "0.12.0"
num = "*"

[workspace]
members = [
    "chaintests/001_crypto_price",
    "chaintests/002_gold_price",
    "chaintests/003_alphavantage",
    "chaintests/004_bitcoin_block_count",
    "chaintests/005_bitcoin_block_hash",
    "chaintests/006_coingecko_volume",
    "chaintests/007_crypto_compare_volume",
    "chaintests/008_eth_gas_station",
    "chaintests/009_open_sky_network",
    "chaintests/010_open_weather_map",
    "chaintests/013_fair_crypto_market_price",
    "chaintests/011_qrng",
    "chaintests/012_yahoo_price",
    "chaindebugtests/allocate",
    "chaindebugtests/wrong_args",
    "chaindebugtests/silly",
    "chaindebugtests/moresilly",

]
