[package]
name = "crypto_price"
version = "0.1.0"
authors = ["bandprotocol"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
owasm = { path = "../../../../owasm" }
