chain-test:
  stage: test
  image: bandprotocol/go-rust:0.1.1
  script:
    - source ~/.profile
    - rustup target add wasm32-unknown-unknown
    - cd chain
    - ./run_tests.sh
  only:
    changes:
      - chain/**/*
