name: Bandchain.js Workflow
on: push

jobs:
  bandchain-test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./helpers/bandchain2.js
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    
    steps:
    - name: Code Checkout
        uses: actions/checkout@v2

    - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

    - name: Install modules
      run: yarn

    - name: Run tests
      run: yarn test