name: Chain Workflow
on:
  push:
    paths:
    - 'chain/**'

jobs:
  chain-test:
    container: bandprotocol/go-rust:0.1.1
    
    steps:
    - name: Code Checkout
      uses: actions/checkout@v2

    - name: Source .profile
      run: ls -a
