name: Owasm Workflow
on:
  push:
    paths:
    - 'owasm/**'

jobs:
  wasm-test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./owasm
    
    steps:
    - name: Code checkout
      uses: actions/checkout@v2

    - name: Install Rust and rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    
    - name: Run owasm tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path owasm/Cargo.toml --all
      working-directory: ${{env.working-directory}}
