name: Scan Workflow
on: push

jobs:
  scan-test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./scan

    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Run yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - run: yarn cypress install
      - run: yarn build
        env:
          RPC_URL: "https://d3n.bandprotocol.com/rest"
          GRAPHQL_URL: "wss://d3n.bandprotocol.com/v1/graphql"
          NETWORK: "GUANYU38"

      - name: Run yarn test
        run: yarn test
        working-directory: ${{env.working-directory}}

      - name: Run yarn integration-test
        run: yarn integration-test
        working-directory: ${{env.working-directory}}
