name: Scan Workflow
on: push

jobs:
  scan-test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./scan

    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Cache node_modules
        id: scan-node-modules-1-cache
        uses: actions/cache@v1
        with:
          path: scan/node_modules
          key: ${{ runner.OS }}-scan-test-1-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn install deps with node_modules cache
        run: |
          yarn install --frozen-lockfile
        if: steps.scan-node-modules-1-cache.outputs.cache-hit != 'true'
        working-directory: ${{env.working-directory}}

      - name: Get yarn cache directory path
        id: yarn-dep-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        name: Setup Yarn dep cache
        id: yarn-dep-cache
        with:
          path: ${{ steps.yarn-dep-1-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-dep-1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-dep-1-

      - name: Yarn install deps with yarn cache
        run: |
          yarn install --frozen-lockfile
        if: steps.scan-node-modules-1-cache.outputs.cache-hit != 'true'
        working-directory: ${{env.working-directory}}

      - name: Run yarn build
        run: yarn build
        env:
          RPC_URL: "https://d3n.bandprotocol.com/rest"
          GRAPHQL_URL: "wss://d3n.bandprotocol.com/v1/graphql"
          NETWORK: "GUANYU38"
        working-directory: ${{env.working-directory}}

      - name: Run yarn test
        run: yarn test
        working-directory: ${{env.working-directory}}

      - name: Run yarn integration-test
        run: yarn integration-test
        working-directory: ${{env.working-directory}}
