name: Scan Workflow
on:
  push:
    paths:
    - 'scan/**'

jobs:
  Scan-Build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./scan

    steps:
    - name: Scan Code Checkout
      uses: actions/checkout@v2

    - name: Scan Build
      run: yarn && yarn bsb -make-world
      working-directory: ${{env.working-directory}}
  
  Scan-Test:
    runs-on: ubuntu-latest
    needs: Scan-Build
    env:
      working-directory: ./scan
    
    steps:
    - name: Test Directory List
      run: ls
      working-directory: ${{env.working-directory}}
