name: Scan Workflow
on:
  push:
    paths:
    - './scan/**'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./scan

    steps:
    - name: Scan Code Checkout
      uses: actions/checkout@v2

    - name: Scan Build
      run: yarn && yarn bsb -make-world
      working-directory: ${{env.working-directory}}
    
    - name: Scan Test
      run: yarn test
      working-directory: ${{env.working-directory}}
