name: Scan Workflow
on: push

jobs:
  scan-test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./scan

    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-dep-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        name: Setup Yarn dep cache
        id: yarn-dep-cache
        with:
          path: ${{ steps.yarn-dep-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-dep-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
              ${{ runner.os }}-yarn-dep-
      - name: Yarn install deps
        run: |
          yarn install --frozen-lockfile
      if: steps.yarn-dep-cache.outputs.cache-hit != 'true'


      - name: Run yarn build
        - run: yarn build
          env:
            RPC_URL: "https://d3n.bandprotocol.com/rest"
            GRAPHQL_URL: "wss://d3n.bandprotocol.com/v1/graphql"
            NETWORK: "GUANYU38"

      - name: Run yarn test
        run: yarn test
        working-directory: ${{env.working-directory}}

      - name: Run yarn integration-test
        run: yarn integration-test
        working-directory: ${{env.working-directory}}
